### ISSUE TITLE
[🐞] Internal server error: Code(20)

### ISSUE THREAD

**Issue by jahwin** [dannyfranca/qwik-router#7]
### Which component is affected?

Qwik Runtime

### Describe the bug

I setting qwik-router as descibed in documentation but am getting error after running and opening project url.
![Screenshot 2024-01-22 at 06 07 22](https://github.com/dannyfranca/qwik-router/assets/31317808/9d5ada30-34b8-482a-873c-96cc9ac732c9)

### Reproduction

no url

### Steps to reproduce

1. create qwik app as library
2. setup qwik-router as in documentation
3. then run

### Additional Information

I seems like there is compatibility issue with "@builder.io/qwik": "1.4.0", which am using. but am not sure

**Comment by dannyfranca** [comment]
@jahwin, update your package to the latest; it should be fine now.

**Comment by jahwin** [comment]
I have tried with updated version but I got new issue:
![Screenshot 2024-02-04 at 12 47 00](https://github.com/dannyfranca/qwik-router/assets/31317808/14487f5b-6689-41c1-b041-fca30b9c26bb)

You package is using use* outside components which is duplicated on  new qwik versions

![Screenshot 2024-02-04 at 12 50 23](https://github.com/dannyfranca/qwik-router/assets/31317808/7969fe4b-9476-4515-ba67-c298694ad83a)

I tried to look only on that file, am not sure if there is any other files have that issue.

**Comment by dannyfranca** [comment]
This one is expected and not an issue; you are trying to execute initRouter in a non-optimized component. I mentioned this in the documentation.

Qwik optimizations only happen in components created with the `component$` factory. This is Qwik by design; it has nothing to do with the lib.

**Comment by dannyfranca** [comment]
This one is expected and not an issue; you are trying to execute initRouter in a non-optimized component. I mentioned this in the documentation.

Qwik optimizations only happen in components created with the component$ factory. This is Qwik by design; it has nothing to do with the lib.

> I have tried with updated version but I got new issue: ![Screenshot 2024-02-04 at 12 47 00](https://private-user-images.githubusercontent.com/31317808/302097058-14487f5b-6689-41c1-b041-fca30b9c26bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTQzNjYsIm5iZiI6MTcwNzExNDA2NiwicGF0aCI6Ii8zMTMxNzgwOC8zMDIwOTcwNTgtMTQ0ODdmNWItNjY4OS00MWMxLWIwNDEtZmNhMzBiOWMyNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA2MjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OWJjOTE4ODA4NWUxMjhhM2E3YTZmYmY4NmJmZGNhZWJlM2ZlOWQ0MTQzOTZmMWRiZmM5MWIyMWJiYmVlODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1E4QB0NwlSB8Q82GVnYfUFw_PaSlyJIRcjAsnRTsPo)
> 
> You package is using use* outside components which is duplicated on new qwik versions
> 
> ![Screenshot 2024-02-04 at 12 50 23](https://private-user-images.githubusercontent.com/31317808/302097222-7969fe4b-9476-4515-ba67-c298694ad83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTQzNjYsIm5iZiI6MTcwNzExNDA2NiwicGF0aCI6Ii8zMTMxNzgwOC8zMDIwOTcyMjItNzk2OWZlNGItOTQ3Ni00NTE1LWJhNjctYzI5ODY5NGFkODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA2MjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNjkxMjdjNDNjOGM4OTRkMmI0YmVmNDhhMjA3OGQ2OWExYWQ3NWUwZjYwNTIyZjIzYTI5ZjIwZGQ0YjUyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zq1qq_hVcOpDisUD5dYbE-tC9gq7tLfuH3-_rsq6L-g)
> 
> I tried to look only on that file, am not sure if there is any other files have that issue.

This one is expected and not an issue; you are trying to execute initRouter in a non-optimized component. I mentioned this in the documentation.

Qwik optimizations only happen in components created with the component$ factory. This is Qwik by design; it has nothing to do with the lib.

**Comment by dannyfranca** [comment]
> I have tried with updated version but I got new issue: ![Screenshot 2024-02-04 at 12 47 00](https://private-user-images.githubusercontent.com/31317808/302097058-14487f5b-6689-41c1-b041-fca30b9c26bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTQzNjYsIm5iZiI6MTcwNzExNDA2NiwicGF0aCI6Ii8zMTMxNzgwOC8zMDIwOTcwNTgtMTQ0ODdmNWItNjY4OS00MWMxLWIwNDEtZmNhMzBiOWMyNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA2MjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OWJjOTE4ODA4NWUxMjhhM2E3YTZmYmY4NmJmZGNhZWJlM2ZlOWQ0MTQzOTZmMWRiZmM5MWIyMWJiYmVlODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1E4QB0NwlSB8Q82GVnYfUFw_PaSlyJIRcjAsnRTsPo)
> 
> You package is using use* outside components which is duplicated on new qwik versions
> 
> ![Screenshot 2024-02-04 at 12 50 23](https://private-user-images.githubusercontent.com/31317808/302097222-7969fe4b-9476-4515-ba67-c298694ad83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTQzNjYsIm5iZiI6MTcwNzExNDA2NiwicGF0aCI6Ii8zMTMxNzgwOC8zMDIwOTcyMjItNzk2OWZlNGItOTQ3Ni00NTE1LWJhNjctYzI5ODY5NGFkODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA2MjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNjkxMjdjNDNjOGM4OTRkMmI0YmVmNDhhMjA3OGQ2OWExYWQ3NWUwZjYwNTIyZjIzYTI5ZjIwZGQ0YjUyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zq1qq_hVcOpDisUD5dYbE-tC9gq7tLfuH3-_rsq6L-g)
> 
> I tried to look only on that file, am not sure if there is any other files have that issue.

This one is expected and not an issue; you are trying to execute initRouter in a non-optimized component. I mentioned this in the documentation.

Qwik optimizations only happen in components created with the component$ factory. This is Qwik by design; it has nothing to do with the lib.

**Comment by jahwin** [comment]
@dannyfranca  Thank you, now everything is working fine.
